name: FloorIsLava
version: '${project.version}'
main: org.epiccarlito.floorislava.FloorIsLava
api-version: '1.21'
authors: [ EpicCarlito ]
commands:
  floorislava:
    description: "Play FloorIsLava"
    usage: "/floorislava [help, start]"
    aliases: [fl]
permissions:
  floorislava:
    description: Allows access to /floorislava
    default: op